from scanner.models import PatternConfig

CUP_HANDLE_CONFIG = PatternConfig(
    name         = "CUP_HANDLE",
    full_name    = "Cup & Handle",
    version      = "1.0.0",
    color        = "#a78bfa",
    icon         = "☕",
    description  = "U-shaped base with shallow handle consolidation",
    timeframe    = "Swing to position — 4 to 16 weeks",
    min_candles  = 100,
    min_signal_score     = 60,
    min_candidate_score  = 62.0,
    max_candidates       = 20,
    rr_hard_minimum      = 0.8,
    vol_contraction_required = True,
    stage2_min_score     = 45,
    pivot_lookback       = 252,
    weight_signal  = 0.55,
    weight_volume  = 0.20,
    weight_rr      = 0.10,
    weight_stage2  = 0.10,
    weight_rs      = 0.05,
    extras = {
        "min_cup_depth_pct":       12.0,
        "max_cup_depth_pct":       33.0,
        "min_cup_candles":         30,
        "max_cup_candles":         150,
        "lip_tolerance_bottom_pct": 0.95,
        "min_handle_candles":      5,
        "max_handle_candles":      25,
        "max_handle_drop_pct":     12.0,
        "max_handle_slope_pct":    0.1,
        "vol_handle_factor":       0.70,
        "buy_point_buffer":        0.10,
        "bonus_lip_diff_3":        3.0,
        "bonus_vol_ratio_50":      0.50,
        "bonus_vol_ratio_60":      0.60,
        "shape_sym_bottom_inner":  0.35,
        "shape_sym_top_inner":     0.65,
        "shape_sym_bottom_outer":  0.25,
        "shape_sym_top_outer":     0.75,
    }
)
