"""
generate_ts_types.py — Generate TypeScript interfaces from Python DTOs.

Reads the FinalPickDTO and ScanSummaryDTO dataclasses from
models/api_types.py and generates a TypeScript file that the
Next.js frontend can import.

Usage:
    python scripts/generate_ts_types.py

Output:
    frontend/SwingsterV2/apps/web/lib/generated-types.ts
"""

import dataclasses
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.api_types import FinalPickDTO, ScanSummaryDTO


# Python type → TypeScript type mapping
_TYPE_MAP = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "list[str]": "string[]",
    "Optional[str]": "string | null",
    "Optional[int]": "number | null",
    "Optional[float]": "number | null",
}


def _python_type_to_ts(annotation) -> str:
    """Convert a Python type annotation to its TypeScript equivalent."""
    type_str = str(annotation).replace("typing.", "")

    # Handle Optional types
    if hasattr(annotation, "__origin__"):
        import typing
        if annotation.__origin__ is typing.Union:
            # Optional[X] is Union[X, None]
            args = [a for a in annotation.__args__ if a is not type(None)]
            if len(args) == 1:
                base = _python_type_to_ts(args[0])
                return f"{base} | null"
        elif annotation.__origin__ is list:
            inner = _python_type_to_ts(annotation.__args__[0])
            return f"{inner}[]"

    name = getattr(annotation, "__name__", str(annotation))
    return _TYPE_MAP.get(name, _TYPE_MAP.get(type_str, "any"))


def _generate_interface(cls, name: str = None) -> str:
    """Generate a TypeScript interface from a dataclass."""
    name = name or cls.__name__.replace("DTO", "")
    lines = [f"export interface {name} {{"]

    for field in dataclasses.fields(cls):
        ts_type = _python_type_to_ts(field.type)

        # Mark optional fields with ?
        is_optional = field.default is not dataclasses.MISSING or \
                      field.default_factory is not dataclasses.MISSING
        # Also check if the type is Optional (contains null)
        if "null" in ts_type:
            is_optional = True
            key = f"  {field.name}?"
        else:
            key = f"  {field.name}"

        lines.append(f"{key}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def main():
    output_lines = [
        "/**",
        " * AUTO-GENERATED by scripts/generate_ts_types.py",
        " * Do NOT edit manually — regenerate with:",
        " *   python scripts/generate_ts_types.py",
        " *",
        " * Source: models/api_types.py",
        " */",
        "",
        _generate_interface(ScanSummaryDTO, "ScanSummary"),
        "",
        _generate_interface(FinalPickDTO, "FinalPick"),
        "",
    ]

    output = "\n".join(output_lines)

    # Write to frontend
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "frontend", "SwingsterV2", "apps", "web", "lib", "generated-types.ts",
    )
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Generated: {output_path}")
    print(output)


if __name__ == "__main__":
    main()
