/**
 * AUTO-GENERATED by scripts/generate_ts_types.py
 * Do NOT edit manually — regenerate with:
 *   python scripts/generate_ts_types.py
 *
 * Source: models/api_types.py
 */

export interface ScanSummary {
  mode: string;
  total_scanned: number;
  pattern_match_count: number;
  rejected_by_rr: string[];
}

export interface FinalPick {
  rank: number;
  symbol: string;
  pattern: string;
  scan_mode: string;
  composite_score: number;
  conviction: string;
  buy_point: number;
  stop_loss: number;
  target: number;
  rr_ratio: number;
  current_price: number;
  distance_from_buy_pct: number;
  signal_strength: number;
  volume_score: number;
  rr_score: number;
  stage2_score: number;
  rs_score: number;
  judge_verdict: string;
  flags: string;
  pledge_pct?: number | null;
  sector?: string | null;
  target2?: number | null;
  pattern_age?: number | null;
  trend?: string | null;
}
