from scanner.models import PatternConfig

FLAG_POLE_CONFIG = PatternConfig(
    name         = "FLAG_POLE",
    full_name    = "Flag & Pole",
    version      = "1.0.0",
    color        = "#f59e0b",
    icon         = "🚩",
    description  = "Impulsive pole followed by tight orderly consolidation",
    timeframe    = "Short swing — 1 to 4 weeks",
    min_candles  = 30,
    min_signal_score     = 55,
    min_candidate_score  = 57.0,
    max_candidates       = 20,
    rr_hard_minimum      = 0.8,
    vol_contraction_required = True,
    weight_signal  = 0.55,
    weight_volume  = 0.25,
    weight_rr      = 0.05,
    weight_stage2  = 0.10,
    weight_rs      = 0.05,
    extras = {
        "pole_lookback":           60,
        "min_pole_gain_pct":       8.0,
        "min_pole_candles":        3,
        "max_pole_candles":        15,
        "min_flag_candles":        5,
        "max_flag_candles":        20,
        "max_flag_retracement":    35.0,
        "max_flag_slope_pct":      0.1,
        "vol_flag_factor":         0.60,
        "buy_point_buffer":        0.10,
        "strong_pole_gain_pct_90": 20.0,
        "strong_pole_gain_pct_70": 12.0,
        "bonus_tight_flag_20":     20.0,
        "bonus_tight_flag_25":     25.0,
        "bonus_vol_ratio_30":      0.30,
        "bonus_vol_ratio_45":      0.45,
    }
)
