from scanner.models import PatternConfig

FLAG_POLE_CONFIG = PatternConfig(
    name         = "FLAG_POLE",
    full_name    = "Flag & Pole",
    version      = "1.0.0",
    color        = "#f59e0b",
    icon         = "🚩",
    description  = "Impulsive pole followed by tight orderly consolidation",
    timeframe    = "Short swing — 1 to 4 weeks",
    min_candles  = 30,
    min_signal_score     = 55,
    min_candidate_score  = 57.0,
    max_candidates       = 50,
    rr_hard_minimum      = 0.8,
    vol_contraction_required = True,
    stage2_min_score     = 55,
    pivot_lookback       = 60,
    weight_signal  = 0.55,
    weight_volume  = 0.25,
    weight_rr      = 0.05,
    weight_stage2  = 0.10,
    weight_rs      = 0.05,
    extras = {
        "pole_lookback":              70,
        "min_pole_candles":           3,
        "max_pole_candles":           30,
        "min_pole_gain_pct":          12.0,
        "max_pole_gain_pct":          150.0,
        "min_pole_velocity":          1.0,
        "min_flag_candles":           3,
        "max_flag_candles":           40,
        "max_flag_retracement":       35.0,
        "max_channel_deviation":      0.035,
        "flag_max_upward_slope":      0.003,
        "flag_min_downward_slope":    -0.008,
        "pole_high_candle_tolerance": 5,
        "vol_flag_factor":            0.60,
        "buy_point_buffer":           0.10,
    }
)
